Related to #165
Added two init-scripts for redhat and ubuntu

diff --git a/misc/config/init-script/jasmind-ubuntu b/misc/config/init-script/jasmind-ubuntu
--- a/misc/config/init-script/jasmind-ubuntu
+++ b/misc/config/init-script/jasmind-ubuntu
@@ -57,11 +57,11 @@ do_start()
 	start-stop-daemon --start --oknodo --quiet --pidfile $PIDFILE  --exec $DAEMON --test > /dev/null \
 		|| return 1
 	start-stop-daemon --start --oknodo --quiet --background --exec $DAEMON \
-                --user=$(id -u $USER) \
-                --group=$(id -g $GROUP) \
-                --pidfile=$PIDFILE \
-                --make-pidfile \
-                $COMMAND -- $COMMAND_ARGS \
+			--user=$(id -u $USER) \
+			--group=$(id -g $GROUP) \
+			--pidfile=$PIDFILE \
+			--make-pidfile \
+			$COMMAND -- $COMMAND_ARGS \
 		|| return 2
 }
 
@@ -89,71 +89,58 @@ do_stop()
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-        echo "NOT IMPLEMENTED YET"
-        return 1
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --oknodo --signal 1 --quiet --pidfile $PIDFILE
-	return 0
+	echo "NOT IMPLEMENTED YET"
+	return 1
 }
 
 case "$1" in
-  start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
-    do_start
-    case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-  ;;
-  stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
+	start)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+	;;
+	stop)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+	;;
+	status)
+		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+	#reload|force-reload)
+	#	NOT IMPLEMENTED
+	#;;
+	restart|force-reload)
+		#
+		# If the "reload" option is implemented then remove the
+		# 'force-reload' alias
+		#
+		log_daemon_msg "Restarting $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1)
+				do_start
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+			;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+			;;
 		esac
 		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
-  *)
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
+	*)
+		echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+		exit 3
 	;;
 esac
 
